apiVersion: v1
kind: Pod
metadata: 
  name: affinity-pod
spec:
  containers:
    - name: affinity
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: NotIn
                values: 
                  - small