apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
  labels:
    app: app1
    type: fe
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: app1
        type: fe
    spec:
     containers:
       - name: nginx
         image: nginx
  replicas: 2
 