apiVersion: v1
kind: ReplicationController
metadata:
  name: rc2
  labels:
    app: app2
    type: be
spec:
  replicas: 3
  template:
    metadata:
      name: busy
      labels:
        app: app2
        type: be
    spec:
      containers:
        - name: busy
          image: busybox
