apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
  labels:
    apps: app1
    tier: fe
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: app1
      tier: fe
  template:
    metadata:
      name: app1-nginx
      labels:
        apps: app1
        tier: fe
    spec:
      containers:
        - name: nginx
          image: nginx